### PR TITLE
Set charset to email

### PR DESCRIPTION
**Pull request by hllavina**
#### What does this PR do?
Updates charset for email sent by html forms to "UTF-8" to avoid special characters created when pasting from Word

#### How can a reviewer manually see the effects of these changes?

https://libraries-dev.mit.edu/forms/dspace-oa-articles.html

#### Requires new or updated plugins, themes, or libraries?
No
#### Requires change to deploy process?
No

### CODE REVIEW

**Review by matt-bernhardt — APPROVED** [review]
Looks good! The test message I sent dealt with the characters that had previously caused problems, and the code change is certainly easy to understand.

**Comment by frrrances** [comment]
Has this change been deployed to prod? I'll email the person who noticed it back if it has to close the loop. Thanks!

**Comment by hllavina** [comment]
I will deploy to prod

**Comment by hllavina** [comment]
The forms are deployed to prod

**Pull request merged**
